global:
  registry: harbor.crazyzone.be/crazyzone
  image: home
  tag: 1.0.0
  #Use an existing secret for your registry
  #existingRegisrySecret: ""
plugwise:
  enabled: false
  device:
    path: /dev/ttyUSB0
resources:
  replicaCount: 1
ingress:
  # If true, the ingress will be created.
  enabled: false
  # Extra annotations for the ingress rule
  annotations: {}
  # Extra labels for the ingress rule
  labels: {}
  className: ""
  #
  # Example:
  # hosts:
  # - host: docs.example.com
  #   paths:
  #   - path: /
  #     pathType: Exact
  #   - host: docs.example.com
  #   paths:
  #     - path: /
  #       pathType: Prefix
  #
  hosts: []
  #
  # Example:
  # tls:
  #   - hosts:
  #     - docs.example.com
  #     secretName: docs-tls
  tls: []
mqtt:
  enabled: true
  broker: "localhost"
  port: 1883
mosquitto:
  enabled: true
  persistence:
    enabled: false
    existingClaim: ""
zigbee2mqtt:
  enabled: true
  zigbee2mqtt:
    homeassistant:
      enabled: false
    timezone: CET
    mqtt:
      server: "mqtt://mosquitto:1883"
    serial:
      port: "tcp://zigbee.crazyzone.be:6638"
    frontend:
      enabled: true
      port: 8080
