global:
  registry: harbor.crazyzone.be/crazyzone
  image: home
  tag: 2.0.0
  imagePullPolicy: IfNotPresent
  #Use an existing secret for your registry
  #existingRegistrySecret: ""
plugwise:
  enabled: false
  device:
    path: /dev/ttyUSB0
resources:
  replicaCount: 1
ingress:
  # If true, the ingress will be created.
  enabled: false
  # Extra annotations for the ingress rule
  annotations: {}
  # Extra labels for the ingress rule
  labels: {}
  className: ""
  #
  # Example:
  # hosts:
  # - host: docs.example.com
  #   paths:
  #   - path: /
  #     pathType: Exact
  #   - host: docs.example.com
  #   paths:
  #     - path: /
  #       pathType: Prefix
  #
  hosts: []
  #
  # Example:
  # tls:
  #   - hosts:
  #     - docs.example.com
  #     secretName: docs-tls
  tls: []
mqtt:
  enabled: true
  broker: "home-mosquitto"
  port: 1883
  persistence:
    enabled: false
    existingClaim: ""
mosquitto:
  enabled: true
  persistence:
    enabled: false
    existingClaim: ""
  service:
    externalTrafficPolicy: null
  config: |
    listener 1883
    listener 9090
    protocol websockets
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
zigbee2mqtt:
  enabled: true
  zigbee2mqtt:
    permit_join: true
    homeassistant:
      enabled: false
    timezone: CET
    mqtt:
      server: "mqtt://home-mosquitto:1883"
    serial:
      port: ""
      adapter: ember
      baudrate: null
      rtscts: null
    frontend:
      enabled: false
      port: 8080
  statefulset:
    storage:
      enabled: false
      storageClassName: "standard"
      existingVolume: ""
