apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $.Chart.Name }}
  name:  {{ $.Chart.Name }}
spec:
  replicas:  {{ $.Values.resources.replicaCount }}
  selector:
    matchLabels:
      app:  {{ $.Chart.Name }}
  template:
    metadata:
      labels:
        app:  {{ $.Chart.Name }}
    spec:
      containers:
      - image: "{{ .Values.global.registry }}/{{ .Values.global.image }}:{{ .Values.global.tag }}"
        name:  {{ $.Chart.Name }}
        volumeMounts:
        - mountPath: {{ $.Values.plugwise.device.path }}
          name: dev-usb0
        securityContext:
          privileged: true
        envFrom:
          - configMapRef:
              name: crazy-home-configmap
        env:
          - name: PLUGWISE_SERIAL_PORT
            value: {{ $.Values.plugwise.device.path }}  
        ports:
        - containerPort: 8080
          name: {{ $.Chart.Name }}
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /readyz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: dev-usb0
        hostPath:
          path: {{ $.Values.plugwise.device.path }}
{{- if $.Values.global.existingRegisrySecret }}          
      imagePullSecrets:
        - name: {{ $.Values.global.existingRegisrySecret }}
{{ end }}